### ISSUE TITLE
finger position are not visible

### ISSUE THREAD

**Issue by yukulele** [flathub/dev.bragefuglseth.Fretboard#6]
Dots are not visible on the flatpak version of Fretboard.

I use a dark theme, I tried to change theme to Adwaita-light, that doesn't fix this issue.

**Comment by yukulele** [comment]
https://github.com/bragefuglseth/fretboard/issues/30

**Comment by bragefuglseth** [comment]
Hi, thanks for your report. Can you tell me how you tried to switch to Adwaita-light? Did you use a command? Fretboard follows the XDG color scheme preference by default, no Adwaita variant should be set manually.

**Comment by yukulele** [comment]
> how you tried to switch to Adwaita-light

I use [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal), I added this environment variable: `GTK_THEME=Adwaita-light`

**Comment by bragefuglseth** [comment]
GTK_THEME is a debug variable, and shouldn’t be used for user restyling because it can lead to cases like this. Fretboard follows the XDG dark mode setting, so things should work properly if you unset GTK_THEME entirely and resort to your system’s built-in light/dark mode setting (given that it supports the portal).
